#  Tourism Data Analysis

##  Data Source
- Source: World Development Indicators (WDI)
- Published by: World Bank
- Last Updated: 24-02-2026

---

## 1️ Arrivals Data (ArrivalsData.csv)

### Indicator
- Name: International Tourism – Number of Arrivals
- Code: ST.INT.ARVL

### Key Points
- Contains number of international tourist arrivals.
- Covers multiple countries.
- Time period: 1960 – 2025.
- Useful to analyze tourism growth trends.
- Helps identify impact of global events (e.g., COVID-19 decline).
- Can be used for forecasting tourism demand.
* **Link:**[World Bank - Tourism Arrival ] *https://data.worldbank.org/indicator/ST.INT.ARVL*
---

## 2️ Expenditure Data (ExpenditureData.csv)

### Indicator
- Name: International Tourism – Expenditure

### Key Points
- Shows total spending by international tourists.
- Helps measure tourism-related economic activity.
- Enables country-wise expenditure comparison.
- Useful for revenue trend analysis.
- Supports economic impact studies.
- **Link:**[World Bank – Tourism Expenditure ] *https://data.worldbank.org/indicator/ST.INT.XPND.CD*

---

## 3️ Receipts Data (ReceiptsData.csv)

### Indicator
- Name: International Tourism – Receipts

### Key Points
- Represents income earned from foreign tourists.
- Measures tourism contribution to national economy.
- Helps analyze foreign exchange earnings.
- Useful for GDP contribution studies.
- Supports financial performance comparison across countries.
- **Link:**[World Bank – Tourism Receipts ] *https://data.worldbank.org/indicator/ST.INT.RCPT.XP.ZS*

---

## Importing Libraries

In [ ]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

##  Loading Dataset

In [3]:
arrivals = pd.read_csv("C:\\Users\\Rishik Reddy\\OneDrive\\Desktop\\Travelnfo\\DataSets\\RawData\\ArrivalsData.csv", skiprows=4)
expenditure = pd.read_csv("C:\\Users\\Rishik Reddy\\OneDrive\\Desktop\\Travelnfo\\DataSets\\RawData\\ExpenditureData.csv", skiprows=4)
receipts = pd.read_csv("C:\\Users\\Rishik Reddy\\OneDrive\\Desktop\\Travelnfo\\DataSets\\RawData\\ReceiptsData.csv", skiprows=4)

In [36]:
arrivals.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Aruba,ABW,"International tourism, number of arrivals",ST.INT.ARVL,NaN,NaN,NaN,NaN,NaN,NaN,...,1758000.00,1863000.00,1897000.00,1951000.0,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,"International tourism, number of arrivals",ST.INT.ARVL,NaN,NaN,NaN,NaN,NaN,NaN,...,37645887.77,38258347.88,41189145.27,39826701.4,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,"International tourism, number of arrivals",ST.INT.ARVL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Africa Western and Central,AFW,"International tourism, number of arrivals",ST.INT.ARVL,NaN,NaN,NaN,NaN,NaN,NaN,...,13150775.34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Angola,AGO,"International tourism, number of arrivals",ST.INT.ARVL,NaN,NaN,NaN,NaN,NaN,NaN,...,397000.00,261000.00,218000.00,218000.0,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
arrivals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 70 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960            0 non-null      float64
 5   1961            0 non-null      float64
 6   1962            0 non-null      float64
 7   1963            0 non-null      float64
 8   1964            0 non-null      float64
 9   1965            0 non-null      float64
 10  1966            0 non-null      float64
 11  1967            0 non-null      float64
 12  1968            0 non-null      float64
 13  1969            0 non-null      float64
 14  1970            0 non-null      float64
 15  1971            0 non-null      float64
 16  1972            0 non-null      float64
 17  1973            0 non-null      float64
 18  1974            0 non-null      float64
 19  1975            0 non-null      float64
 20  1976            0 non-null      float64
 21  1977            0 non-null      float64
 22  1978            0 non-null      float64
 23  1979            0 non-null      float64
 24  1980            0 non-null      float64
 25  1981            0 non-null      float64
 26  1982            0 non-null      float64
 27  1983            0 non-null      float64
 28  1984            0 non-null      float64
 29  1985            0 non-null      float64
 30  1986            0 non-null      float64
 31  1987            0 non-null      float64
 32  1988            0 non-null      float64
 33  1989            0 non-null      float64
 34  1990            0 non-null      float64
 35  1991            0 non-null      float64
 36  1992            0 non-null      float64
 37  1993            0 non-null      float64
 38  1994            0 non-null      float64
 39  1995            207 non-null    float64
 40  1996            214 non-null    float64
 41  1997            215 non-null    float64
 42  1998            215 non-null    float64
 43  1999            215 non-null    float64
 44  2000            217 non-null    float64
 45  2001            219 non-null    float64
 46  2002            216 non-null    float64
 47  2003            220 non-null    float64
 48  2004            220 non-null    float64
 49  2005            225 non-null    float64
 50  2006            229 non-null    float64
 51  2007            233 non-null    float64
 52  2008            237 non-null    float64
 53  2009            234 non-null    float64
 54  2010            237 non-null    float64
 55  2011            238 non-null    float64
 56  2012            237 non-null    float64
 57  2013            237 non-null    float64
 58  2014            236 non-null    float64
 59  2015            240 non-null    float64
 60  2016            240 non-null    float64
 61  2017            234 non-null    float64
 62  2018            230 non-null    float64
 63  2019            223 non-null    float64
 64  2020            132 non-null    float64
 65  2021            0 non-null      float64
 66  2022            0 non-null      float64
 67  2023            0 non-null      float64
 68  2024            0 non-null      float64
 69  2025            0 non-null      float64
dtypes: float64(66), object(4)
memory usage: 145.6+ KB

In [38]:
arrivals.shape
print("Number of rows:", arrivals.shape[0]) 
print("Number of columns:", arrivals.shape[1])

Number of rows: 266
Number of columns: 70

## Checking Null Values

In [39]:
arrivals.isnull().sum()

Country Name        0
Country Code        0
Indicator Name      0
Indicator Code      0
1960              266
                 ...
2021              266
2022              266
2023              266
2024              266
2025              266
Length: 70, dtype: int64

## Remove Unnecessary Columns

In [41]:
cols_to_drop = ['Indicator Name', 'Indicator Code']
arrivals = arrivals.drop(columns=cols_to_drop)
expenditure = expenditure.drop(columns=cols_to_drop)
receipts = receipts.drop(columns=cols_to_drop)

In [43]:
arrivals.columns

Index(['Country Name', 'Country Code', '2005', '2006', '2007', '2008', '2009',
       '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018',
       '2019', '2020', '2021', '2022', '2023'],
      dtype='object')

## Keep Relevant Years

In [10]:
years = [str(year) for year in range(2005, 2024)]

arrivals = arrivals[['Country Name','Country Code'] + years]
expenditure = expenditure[['Country Name','Country Code'] + years]
receipts = receipts[['Country Name','Country Code'] + years]

In [11]:
arrivals.columns

Index(['Country Name', 'Country Code', '2005', '2006', '2007', '2008', '2009',
       '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018',
       '2019', '2020', '2021', '2022', '2023'],
      dtype='object')

## Remove Aggregated Regions

In [7]:
remove_words = "World|income|OECD|Asia|Europe|Africa|America"

arrivals = arrivals[~arrivals['Country Name'].str.contains(remove_words)]
expenditure = expenditure[~expenditure['Country Name'].str.contains(remove_words)]
receipts = receipts[~receipts['Country Name'].str.contains(remove_words)]

In [9]:
arrivals.info()

<class 'pandas.core.frame.DataFrame'>
Index: 232 entries, 0 to 265
Data columns (total 21 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country Name  232 non-null    object
 1   Country Code  232 non-null    object
 2   2005          191 non-null    float64
 3   2006          195 non-null    float64
 4   2007          199 non-null    float64
 5   2008          203 non-null    float64
 6   2009          200 non-null    float64
 7   2010          203 non-null    float64
 8   2011          204 non-null    float64
 9   2012          203 non-null    float64
 10  2013          203 non-null    float64
 11  2014          202 non-null    float64
 12  2015          206 non-null    float64
 13  2016          206 non-null    float64
 14  2017          201 non-null    float64
 15  2018          197 non-null    float64
 16  2019          190 non-null    float64
 17  2020          130 non-null    float64
 18  2021          0 non-null      float64
 19  2022          0 non-null      float64
 20  2023          0 non-null      float64
dtypes: float64(19), object(2)
memory usage: 39.9+ KB

## Convert from Wide → Long Format

In [14]:
arrivals_long = arrivals.melt(
    id_vars=['Country Name','Country Code'],
    var_name='Year',
    value_name='Arrivals'
)

expenditure_long = expenditure.melt(
    id_vars=['Country Name','Country Code'],
    var_name='Year',
    value_name='Expenditure'
)

In [47]:
arrivals_long.head()

                  Country Name Country Code  Year      Arrivals
0                        Aruba          ABW  2005  1.286000e+06
1  Africa Eastern and Southern          AFE  2005  1.991757e+07
2                  Afghanistan          AFG  2005           NaN
3   Africa Western and Central          AFW  2005  6.320832e+06
4                       Angola          AGO  2005  2.100000e+05

## Merge Datasets

In [15]:
merged = arrivals_long.merge(
    expenditure_long,
    on=['Country Name','Country Code','Year'],
    how='inner'
)

In [49]:
merged.head()

                  Country Name Country Code  Year      Arrivals   Expenditure
0                        Aruba          ABW  2005  1.286000e+06  2.500000e+08
1  Africa Eastern and Southern          AFE  2005  1.991757e+07  9.095631e+09
2                  Afghanistan          AFG  2005           NaN           NaN
3   Africa Western and Central          AFW  2005  6.320832e+06  3.182179e+09
4                       Angola          AGO  2005  2.100000e+05  1.350000e+08

In [19]:
merged.to_csv("DataSets/Merged_Tourism_Dataset.csv", index=False)

In [20]:
import os
os.listdir("DataSets")

['ArrivalsData.csv',
 'ExpenditureData.csv',
 'Merged_Tourism_Dataset.csv',
 'ReceiptsData.csv']